# Generated by Django 5.2.8 on 2025-11-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Entorno',
                'verbose_name_plural': 'Entornos',
                'db_table': 'testsuite.entorno',
            },
        ),
        migrations.CreateModel(
            name='CasoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casoprueba_estado', to='commons.estado')),
                ('entorno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testsuite.entorno')),
            ],
            options={
                'verbose_name': 'Caso Prueba',
                'verbose_name_plural': 'Casos Pruebas',
                'db_table': 'testsuite.casoprueba',
            },
        ),
        migrations.CreateModel(
            name='EjecucionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('observaciones', models.TextField(blank=True)),
                ('resultado', models.CharField(max_length=100)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.file')),
                ('caso_prueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testsuite.casoprueba')),
                ('ejecutado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecucionprueba_estado', to='commons.estado')),
            ],
            options={
                'verbose_name': 'Ejecución Prueba',
                'verbose_name_plural': 'Ejecuciones Pruebas',
                'db_table': 'testsuite.ejecucionprueba',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Test Suite',
                'verbose_name_plural': 'Test Suites',
                'db_table': 'testsuite.testsuite',
            },
        ),
        migrations.AddField(
            model_name='casoprueba',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testsuite.testsuite'),
        ),
    ]
