# Generated by Django 5.2.8 on 2025-11-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioBug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('comentario', models.TextField()),
            ],
            options={
                'verbose_name': 'Comentario Bug',
                'verbose_name_plural': 'Comentarios Bugs',
                'db_table': 'auth.comentario_bug',
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.file')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_asignados', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_estado', to='commons.estado')),
                ('prioridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prioridad', to='commons.prioridad', verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Bug',
                'verbose_name_plural': 'Bugs',
                'db_table': 'auth.bug',
            },
        ),
    ]
