# Generated by Django 5.2.8 on 2025-11-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugtracker', '0001_initial'),
        ('commons', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='bug',
            name='reportado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs_reportados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bug',
            name='severidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='severidad', to='commons.prioridad', verbose_name='Severidad'),
        ),
        migrations.AddField(
            model_name='bug',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint', to='proyectos.sprint'),
        ),
        migrations.AddField(
            model_name='comentariobug',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.file'),
        ),
        migrations.AddField(
            model_name='comentariobug',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.bug'),
        ),
        migrations.AddField(
            model_name='comentariobug',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
