# Generated by Django 5.2.8 on 2025-11-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        ('proyectos', '0001_initial'),
        ('testsuite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.estado')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto')),
                ('testsuite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testsuite.testsuite')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.tipo')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reports.reporte',
            },
        ),
        migrations.CreateModel(
            name='ArchivoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.file')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporte')),
            ],
            options={
                'verbose_name': 'Archivo Reporte',
                'verbose_name_plural': 'Archivos Reportes',
                'db_table': 'reports.archivoreporte',
            },
        ),
    ]
