# Generated by Django 5.2.8 on 2025-11-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=200, verbose_name='Division regiona/ Departamento')),
            ],
            options={
                'verbose_name': 'Division Regional',
                'verbose_name_plural': 'Divisiones Regionales / Departamentos',
                'db_table': 'auth.division_regional',
            },
        ),
        migrations.CreateModel(
            name='DominioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Dominio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Dominio Permitido',
                'verbose_name_plural': 'Dominios Permitidos',
                'db_table': 'auth.dominio_permitido',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=200)),
                ('prefijo', models.CharField(max_length=200)),
                ('codigo_iso', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'auth.pais',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nick', models.CharField(max_length=100, unique=True, verbose_name='Nickname')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('idioma', models.CharField(default='es', max_length=10, verbose_name='Idioma')),
                ('zona_horaria', models.CharField(default='UTC', max_length=50, verbose_name='Zona Horaria')),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('mfa_fallos_consecutivos', models.IntegerField(default=0)),
                ('mfa_nivel_bloqueo', models.IntegerField(default=0)),
                ('mfa_bloqueo_expiracion', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al Admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('roles', models.ManyToManyField(blank=True, related_name='usuarios', to='commons.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth.usuario',
            },
        ),
        migrations.CreateModel(
            name='AutenticacionMultifactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('codigo_verificacion', models.CharField(max_length=6)),
                ('fecha_expiracion', models.DateTimeField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_mfa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autenticación Multifactor',
                'verbose_name_plural': 'Autenticaciones Multifactor',
                'db_table': 'auth.mfa',
            },
        ),
        migrations.CreateModel(
            name='DivisionLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=200, verbose_name='Division local/ Municipio')),
                ('division_regional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacion.divisionregional')),
            ],
            options={
                'verbose_name': 'Division Local',
                'verbose_name_plural': 'Divisiones Locales / Municipios',
                'db_table': 'auth.division_local',
            },
        ),
        migrations.AddField(
            model_name='divisionregional',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacion.pais'),
        ),
        migrations.CreateModel(
            name='TokenActivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_activacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Activación',
                'verbose_name_plural': 'Tokens de Activación',
                'db_table': 'auth.token_activacion',
            },
        ),
    ]
