# Generated by Django 5.2.8 on 2025-11-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autenticacionmultifactor',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
