# Generated by Django 5.2.8 on 2025-11-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugtracker', '0002_initial'),
        ('commons', '0001_initial'),
        ('proyectos', '0001_initial'),
        ('reports', '0001_initial'),
        ('testsuite', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('descripcion', models.TextField(blank=True)),
                ('bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugtracker.bug')),
                ('comentario_bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugtracker.comentariobug')),
                ('comentario_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.comentarioticket')),
                ('ejecucion_prueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testsuite.ejecucionprueba')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.estado')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto')),
                ('reportes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporte')),
                ('testsuite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testsuite.testsuite')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'db_table': 'auth.historial',
            },
        ),
        migrations.CreateModel(
            name='DetalleHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='historial.historial')),
            ],
            options={
                'verbose_name': 'Detalle Historial',
                'verbose_name_plural': 'Detalles Historiales',
                'db_table': 'auth.detallehistorial',
            },
        ),
    ]
