# Generated by Django 5.2.8 on 2025-11-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('empresas', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa_proyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_proyectos', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='empresa_proyecto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_proyectos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='proyecto',
            field=models.ManyToManyField(related_name='empresas_proyectos', through='empresas.Empresa_Proyecto', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='empresa_usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_usuario', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='empresa_usuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.ManyToManyField(related_name='empresas', through='empresas.Empresa_Usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.divisionlocal'),
        ),
        migrations.AlterUniqueTogether(
            name='empresa_proyecto',
            unique_together={('empresa', 'proyecto', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='empresa_usuario',
            unique_together={('usuario', 'empresa')},
        ),
    ]
